X=MsgBox("Error while opening Computer. Do you want to fix this error?",4+64,"Computer")
X=MsgBox("Unable to fix this error. Do you want to scan this computer?",3+48,"Computer")
X=MsgBox("Alert! Harmfull software detected. Attempt to resolve the problem?",3+16,"Alert!") 
X=MsgBox("Unable to delete the harmful software.",1+64,"Critical Error")
X=MsgBox("Malware triggered, and compromised the security of WIndows and other software. Attempting to fully remove...",2+16,"Alert") 
X=MsgBox("Deleting System Files...",2+16,"File Deletion") 
X=MsgBox("Uploading data. Do you want to terminate the process?",4+16,"File Transfer")
X=MsgBox("Could not stop. File transfer completed",1+64,"Completed")
set objShell = wscript.CreateObject("wscript.shell")
objShell.Run "shutdown.exe /R /T 5 /C ""dude you just got pranked."" "
